### ISSUE TITLE
Can this repo be made public?

### ISSUE THREAD

**Issue by adolski** [UIUCLibrary/uiuc_lib_ad#6]
@jtgorman Some of the SCARS apps in the medusa-project org are public, and it's not straightforward to add this gem to their Gemfiles because of the repo being private. So, could this repo be made public?

I have already inquired about making some of our SCARS apps private, but this was vetoed by the powers that be.

**Comment by jtgorman** [comment]
Done, you should be able to pull in via a git: in the gem line now
